### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#8]
- [x] 斜体的本科 bib 英文文献名
- [x] author-year 式的参考文献
- [x] Windows 的 make.bat
- [ ] 英语支持
- [x] 写 main.tex 的 demo
- [ ] 行距问题待确认
- [x] 数学环境
- [x] 写 manual
- [x] 目录标题中间需要空格
- [x] 本科目录章后需要空行
- [x] “作者姓名” 粗度
- [x] 本科论文支持
- [x] dtx 封装
- [x] 完善 Makefile，chapters/*.tex的依赖性
- [x] longtable
- [x] PDF蓝色链接打印效果
- [x] 参考文献的页眉
- [x] 中英文论文标题未加粗
- [x] 英文标题行距
- [x] 作者姓名没有距离左边界6cm
- [x] 英文作者姓名，不是严格30磅
- [x] 密级
- [x] 书脊
- [x] abstract未使用Arial字体, abstract全大写
- [x] 目录缩进的字符宽度由字体决定
- [x] 目录中段前段后的设置
- [x] 目录的书签
- [x] 图、表的书签
- [x] 参考文献及其标签
- [x] 致谢的书签
- [x] 符号对照表
- [x] 脚注的编号？
- [x] 空白页不显示页码？
- [x] 图和表的题注
- [x] 页码位置
- [x] table caption aboveskip=belowskip?
- [x] 公式编号的字号为10.5磅
- [x] 数学字体与 Times New Roman 匹配

**Comment by zepinglee** [comment]
“图和表的题注”是有哪些问题？我还没看出来啊

**Comment by seisman** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/3974108/9154255/81aaf0be-3eb8-11e5-8ca9-3cd9e93be104.png)

Note那段文字是图的题注，这一部分的几个要求，目前还未实现。

**Comment by zepinglee** [comment]
这优点蛋疼啊，我试试用bicaption宏包去做

**Comment by zepinglee** [comment]
用caption*{}做好了，因为不能显示captionlabel所以只用自己做了悬挂缩进。
table caption aboveskip=belowskip 是什么意思？我觉得没什么问题

**Comment by zepinglee** [comment]
需要用longtable的人应该不多，让他们自己去处理好了。
table caption aboveskip=belowskip? 是什么意思？

**Comment by zepinglee** [comment]
还有页码位置在 https://github.com/ywgATustcbbs/ustcthesis/issues/12 讨论过，研究生统一放在页脚外侧。

**Comment by zepinglee** [comment]
诶？现在的怎么是居中的？这不能忍啊！

学校的《规范》有两条矛盾的规定，我们只能理解为 or 的逻辑关系，显然双面打印放在外侧好看啊。

**Comment by seisman** [comment]
1. 规范中，figure caption段前6磅，段后12磅，table caption段前6磅，段后6磅。我当时应该是在质疑规范为什么要这么设计。
2. `longtable`还是建议加进去，对于某些做实验的人来说算是比较常用的功能。而对于不需要使用longtable的人来说，也只是额外多加载了一个宏包，编译速度可能慢一点而已，没有其他额外的影响。
3. 页码的问题，研究生双面打印放右边，本科生单面打印放中间。这应该算是比较合适的处理方法。

**Comment by zepinglee** [comment]
1. 就这样写懒得管了
2. 作为数学系的我没用过这玩意，以后再做
3. 同意

我刚刚加入了修改了数学字体：
原来fontspec会把mathrm{}的字体设置成Times New Roman，这样\log \sin就太粗了，跟mathnormal不协调；我改成默认的数学字体样式了。

**Comment by seisman** [comment]
生成的PDF蓝色链接，彩色打印机打印出来的效果也是彩色的。如果是想解决这个问题的话，可以设置`colorlinks=false, pdfborder=0 0 0`。

**Comment by zepinglee** [comment]
我觉得也做成一个选项好了，默认print，可选择pdf使链接变蓝色

**Comment by seisman** [comment]
`print`模式下hyperref要使用`pdfborder=0 0 0`，否则链接处会出现红色方框，且方框的尺寸是有问题的。

**Comment by zepinglee** [comment]
修改好了

**Comment by ywgATustcbbs** [comment]
pdf中的链接有红色方框的话是不影响打印的，所以可以简单的把链接文字调整为黑色，其他的不需要特殊处理

**Comment by seisman** [comment]
红色方框是不会打印，不过在我的PDF阅读器下红色方框的高度比字高要小不少。

而且之前就有人提过红色边框的问题，大多数人在没正式打印之前是不知道红色方框不会被打印这个事情的。
